# --- Service Nodes ---

[media_servers]
media ansible_host=192.168.4.200 ansible_user=patrick

[storage_servers]
vault ansible_host=192.168.4.210 ansible_user=patrick

[hypervisors]
forge ansible_host=192.168.4.220 ansible_user=root

[monitoring]
monitor ansible_host=192.168.4.232 ansible_user=patrick

[network]
vpn ansible_host=192.168.4.230 ansible_user=patrick

[ingress]
proxy ansible_host=192.168.4.231 ansible_user=patrick


# --- Policy Groups ---

[managed]
media
vault
monitor
vpn
proxy

[proxmox]
forge

[tunnel_connector]
proxy


[all:children]
media_servers
storage_servers
hypervisors
monitoring
network
ingress
managed
proxmox
tunnel_connector

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=/home/patrick/.ssh/id_ed25519
